### ISSUE TITLE
Write Internal docstrings

### ISSUE THREAD

**Issue by LouisDesdoigts** [LouisDesdoigts/dLux#1]

**Comment by Jordan-Dennis** [comment]
While I document I will write these out but they will need checking as I will probably misinterpret some of the logic.

**Comment by Jordan-Dennis** [comment]
As a related note are we planning to type annotate the code? For example:
```py 
def __call__(self, image):
```
would become:
```py
def __call__(self, image: ndarray) -> ndarray:
```

**Comment by Jordan-Dennis** [comment]
Hi all,
Another update from me regarding the current state of the issues. This particular one is fully complete for the backend files `wavefronts.py` and `propagators.py` as well as the front end file `layers.py`. I would like to note that `layers.py` is pending a restructure following the week surrounding the JWST data release, so this documentation is primarily temporary. 

Regards

Jordan﻿

**Comment by LouisDesdoigts** [comment]
I would consider this 'done' as the core parts of the package all have mostly complete docstrings. Not worth having an open issue for.
