### ISSUE TITLE
Change 'ApplyAperture' to 'TransmissiveOptic'

### ISSUE THREAD

**Issue by LouisDesdoigts** [LouisDesdoigts/dLux#101]
This is a more accurate and descriptive name for this layer.

**Comment by Jordan-Dennis** [comment]
I like this name change.

**Comment by benjaminpope** [comment]
I agree. When we change this and also change `Physical` to `Cartesian` we should remember to change them in `docs/notebooks/*.ipynb` before committing to `main`.

**Comment by benjaminpope** [comment]
Make sure to propagate this through the docs notebooks!

———————————————
Dr Benjamin Pope (he/him)
Lecturer in Astrophysics
University of Queensland
benjaminpope.github.io
________________________________

**Comment by LouisDesdoigts** [comment]
Yup I fixed up all the doc notebooks too
