### ISSUE TITLE
Cache MFT matrices rather than recalculating every time?

### ISSUE THREAD

**Issue by benjaminpope** [LouisDesdoigts/dLux#103]
title

**Comment by Jordan-Dennis** [comment]
From memory it seems to work fine interacting with `equinox` and `jax` to use `functools.cached_property`. This is as easy as adding a decorator so it is more or less free speed. The other option is just to calculate and store them in the `__init__` method.

**Comment by LouisDesdoigts** [comment]
Yeah awesome, the only issue I potential issue I see is if the wavelength values themselves are optimised. I don't really see a particular use case for this (other than potentially trying to find the width of a bandpass?), but if so it would basically just chew up more memory each iteration... Probably not an issue but there are some cases it might crash some things. Potential solution is to print a warning when trying to do so, but we would only be able to do this once we have integrated some filter_spec functionality.

**Comment by Jordan-Dennis** [comment]
Ok so I just tried the follow example to check:
```py
class A(eqx.Module):
    @cached_property
    def _cahced(self, a):
        return a
```
and it failed to run which is worrying :grimacing:. The error was cryptic though `missing parameter` no matter how many were passed. I can't remember if I had solved/run into this before.

**Comment by benjaminpope** [comment]
I assume when you ran it you had cached spelled correctly…

———————————————
Dr Benjamin Pope (he/him)
Lecturer in Astrophysics
University of Queensland
benjaminpope.github.io
________________________________

**Comment by LouisDesdoigts** [comment]
Caching is not possible without adding our own caching methods because arrays are not hashable. It is likely possible to write our own, but this is not necessary for now.
