### ISSUE TITLE
Build information preserving Fourier Rotation layer

### ISSUE THREAD

**Issue by LouisDesdoigts** [LouisDesdoigts/dLux#104]
So the regular interpolation rotations do not preserve information, and this is worse for us since we are limited to linear interpolation in Jax. There is a Fourier rotation method that completely preserves information by applying 3 separate 1d FFTs with phase slopes that we should use instead of the current method. Anthony Cheetam send me some old code to achieve this so we should turn this into a layer for us to use, particularly with (small) rotations being applied for most of the JWST detectors.

```py

import numpy as np
from scipy import ndimage
try:
    import pyfftw.interfaces.scipy_fftpack as fftpack
except:
    from scipy import fftpack

def fft_3shear_rotate_pad(in_frame, alpha, pad=4, return_full = False):
	"""
	3 FFT shear based rotation, following Larkin et al 1997

	in_frame: the numpy array which has to be rotated
	alpha: the rotation alpha in degrees
	pad: the padding factor

	The following options were removed because they didn't work:
		x1,x2: the borders of the original image in x
		y1,y2: the borders of the original image in y

	One side effect of this program is that the image gains two columns and two rows.
	This is necessary to avoid problems with the different choice of centre between
	GRAPHIC and numpy

	Return the rotated array
	"""
	
	#################################################
	# Check alpha validity and correcting if needed
	#################################################
	alpha=1.*alpha-360*np.floor(alpha/360)

	# We need to add some extra rows since np.rot90 has a different definition of the centre
	temp = np.zeros((in_frame.shape[0]+3,in_frame.shape[1]+3))+np.nan
	temp[1:in_frame.shape[0]+1,1:in_frame.shape[1]+1]=in_frame
	in_frame = temp

	# FFT rotation only work in the -45:+45 range
	if alpha > 45 and alpha < 135:
		in_frame=np.rot90(in_frame, k=1)
		alpha_rad=-np.deg2rad(alpha-90)
	elif alpha > 135 and alpha < 225:
		in_frame=np.rot90(in_frame, k=2)
		alpha_rad=-np.deg2rad(alpha-180)
	elif alpha > 225 and alpha < 315:
		in_frame=np.rot90(in_frame, k=3)
		alpha_rad=-np.deg2rad(alpha-270)
	else:
		alpha_rad=-np.deg2rad(alpha)

		 # Remove one extra row
	in_frame = in_frame[:-1,:-1]

	###################################
	# Preparing the frame for rotation
	###################################

	# Calculate the position that the input array will be in the padded array to simplify
	#  some lines of code later 
	px1=np.int(((pad-1)/2.)*in_frame.shape[0])
	px2=np.int(((pad+1)/2.)*in_frame.shape[0])
	py1=np.int(((pad-1)/2.)*in_frame.shape[1])
	py2=np.int(((pad+1)/2.)*in_frame.shape[1])

	# Make the padded array	
	pad_frame=np.ones((in_frame.shape[0]*pad,in_frame.shape[1]*pad))*np.NaN
	pad_mask=np.ones((pad_frame.shape), dtype=bool)
	pad_frame[px1:px2,py1:py2]=in_frame
	pad_mask[px1:px2,py1:py2]=np.where(np.isnan(in_frame),True,False)
	
	# Rotate the mask, to know what part is actually the image
	pad_mask=ndimage.interpolation.rotate(pad_mask, np.rad2deg(-alpha_rad),
		  reshape=False, order=0, mode='constant', cval=True, prefilter=False)

	# Replace part outside the image which are NaN by 0, and go into Fourier space.
	pad_frame=np.where(np.isnan(pad_frame),0.,pad_frame)


	###############################
	# Rotation in Fourier space
	###############################
	a=np.tan(alpha_rad/2.)
	b=-np.sin(alpha_rad)

	M=-2j*np.pi*np.ones(pad_frame.shape)
	N=fftpack.fftfreq(pad_frame.shape[0])

	X=np.arange(-pad_frame.shape[0]/2.,pad_frame.shape[0]/2.)#/pad_frame.shape[0]

	pad_x=fftpack.ifft((fftpack.fft(pad_frame, axis=0,overwrite_x=True).T*
		np.exp(a*((M*N).T*X).T)).T, axis=0,overwrite_x=True)
	pad_xy=fftpack.ifft(fftpack.fft(pad_x,axis=1,overwrite_x=True)*
		np.exp(b*(M*X).T*N), axis=1,overwrite_x=True)
	pad_xyx=fftpack.ifft((fftpack.fft(pad_xy, axis=0,overwrite_x=True).T*
		np.exp(a*((M*N).T*X).T)).T,axis=0,overwrite_x=True)

	# Go back to real space
	# Put back to NaN pixels outside the image.

	pad_xyx[pad_mask]=np.NaN


	if return_full:
		return np.real(pad_xyx).copy()
	else:
		return np.real(pad_xyx[px1:px2,py1:py2]).copy()
```

**Comment by Jordan-Dennis** [comment]
After discussing this with @benjaminpope we have decided to use linear interpolation where `scipy.ndimage.interpolation.spline_1d` is used internally by `scipy.ndimage.interpolation.rotate`. I will lift this out of the `Wavefront` class and into `utils`.

**Comment by LouisDesdoigts** [comment]
Hey @Jordan-Dennis I already have built a paraxial rotation code in jax 😉

```
def paraxial_rotate(array, rotation, order=1):
    """
    array: Array to rotate
    rotation: rotation angle in degrees
    order: interpolation order, supports 0 and 1

    Basically a jax version of scipy.ndimage.rotate - Contribute to Jax?
    """

    # Get coords arrays
    npix = array.shape[0]
    centre = (npix-1)/2
    x_pixels, y_pixels = get_pixel_positions(npix)
    rs, phis = cart2polar(x_pixels, y_pixels)
    phis += deg2rad(rotation)
    coordinates_rot = np.roll(polar2cart(rs, phis) + centre, shift=1, axis=0)
    rotated = map_coordinates(array, coordinates_rot, order=order)
    return rotated
```

This could be trivially extended to include shifts as well if you need

**Comment by Jordan-Dennis** [comment]
Ok perfect, where does that one live? I could not find it in "coordinates.py" or "helpers.py".

**Comment by LouisDesdoigts** [comment]
This is just a local version I built for the JWST stuff - Haven't pushed it to main

**Comment by Jordan-Dennis** [comment]
Ok cool. I have copy pasted it anyway.

**Comment by Jordan-Dennis** [comment]
@LouisDesdoigts have you ever run the code above? I'm just finding things that are syntax errors which are concerning. Naturally, I did not check it before I started to change things.

**Comment by LouisDesdoigts** [comment]
Worked fine for me. Probably just to do with the the changes of `get_pixel_positions` or something. Probably just needs an import change

**Comment by Jordan-Dennis** [comment]
Yeah so I re copy pasted it and it seems to work fine. I'll post the images once I have got home.

**Comment by Jordan-Dennis** [comment]
So I have finished this although I did it in a different repo. I will try and rebase the commits and then push it in under `dev` in a new branch `InformationPreservingRotations`.

**Comment by benjaminpope** [comment]
Nice! Merge away!

**Comment by Jordan-Dennis** [comment]
I will state however, that for my toy/test example:
![image](https://user-images.githubusercontent.com/93350879/187351325-8fd3a12b-f224-488e-967f-368859df7b2d.png)
![image](https://user-images.githubusercontent.com/93350879/187351517-b5428aa0-d745-4dec-8299-f1c3af77199c.png)
And this matches the output of the `numpy` program. Side by side you can see that the colors have changed. @LouisDesdoigts, what are your thoughts.

**Comment by benjaminpope** [comment]
Bit alarming - what if we expand the field of view so you fully contain the rotated square? Perhaps Fourier power is being lost.

———————————————
Dr Benjamin Pope (he/him)
Lecturer in Astrophysics
University of Queensland
benjaminpope.github.io
________________________________

**Comment by Jordan-Dennis** [comment]
The code works on a 4 times padded array and then crops it before returning, so I would be surprised if this is the case. In general, I am very sceptical as the function calls the linear interpolated rotate under the hood and then applies a large amount of complex Fourier transforms over the top, but I am not sure how that "preserves information".

**Comment by LouisDesdoigts** [comment]
Yeah I would guess that this would be one the worst test-cases for this method. Hard edges and sharp boundaries are not what we will be working with anyway. Similarly I would also test rotating it back and checking that it gives back the same result.

The interpolation step is only there to find which pixels will remain within the image after the rotation. You can see in this line `pad_xyx[pad_mask]=np.NaN`. 

What makes this 'information preserving' is that you can rotate something an arbitrary number of times and never lose information. Ie rotating 90 degrees should give you the same answer and rotating 1 degree 90 times. 

I would just test this on a few Gaussian blobs within the rotation field, and see if you can rotate back and forth a bunch of times without degradation, etc.

**Comment by Jordan-Dennis** [comment]
Alright, so I am just adding this on a branch now so I can make a PR. I thought I would adapt this thread for discussions regarding the optimisation of the code, which honestly tanks. I was wondering if it would be possible to use either an MFT or the accelerated symmetric (two-sided) MFT from `xaosim` to make this faster. Obviously @benjaminpope and @LouisDesdoigts you are both more experienced in how to chose the sampling. I saw that we had helper functions `nyquist_xxx` now so I was wondered if these could be used and if not, if it would be possible to create a function that given an "image" array could generate a sampling factor.

**Comment by benjaminpope** [comment]
I reckon this is a future problem

**Comment by benjaminpope** [comment]
FFT will be better than MFT here, as the whole point of MFTs is they allow you to adjust sampling to look at high resolution at a small region of the output. Meanwhile FFTs transform the whole input array preserving all information up to the Nyquist frequency - which is what you want to do for an information-preserving rotation.
