### ISSUE TITLE
Serialisation

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#111]
Hi all,
I was wondering if we wanted to look into a feature that allowed `dLux` to interface with configuration files. The pros:
 - Models are easy to share and replicate: Rather than sharing a complex `jupyter otebook` with both the model initialisation and science code a `.json` file can be passed and a model initialised in a single line of code, i.e. `dLux.osys_from_file()`.
 - Model is separated from modelling code. 
 - Less repetition of code constructing models: If you want to use the same model in different files instead of making a helper script that initialises the model and then importing it, just run `dLux.osys_from_file()`. 

As always let me know your thoughts,

Jordan

**Comment by benjaminpope** [comment]
Yes - good idea. Would mean we can save and load precompiled models like we do in `ticktack`. Could do this for the main JWST, HST instruments, et cetera...

**Comment by Jordan-Dennis** [comment]
I'm looking into this for the Hubble model briefly this afternoon because I think it will save time in the future. I think that `.json` is the way to go opposed to `.yaml`, `.toml` ect. since it has a nice nested structure which is essentially "isomorphic" to `dLux`'s internal representations. `json`, the package, is also part of the standard library so we avoid creating another dependency.

**Comment by benjaminpope** [comment]
I agree - `.json` is a sensible standard for holding what is basically a dict or a list. If we had to hold large files - eg apertures defined by custom static arrays - I would suggest `.hd5`.

**Comment by Jordan-Dennis** [comment]
I had a look into this, this afternoon and it does not seem too tricky. I was able to write a `.json` file for the hubble model and get it read into python. I didn't really try and write the `dLux` interface though because I thought it would take too long.

**Comment by benjaminpope** [comment]
Awesome! Not sure what you mean about the `dLux` interface versus being able to write and read the `.json` - these are more or less the same thing, just need to wrap it up in some nice functions.

**Comment by Jordan-Dennis** [comment]
Alright so I think I have thought of a good way to implement this. Step 1: we create and `Encodable` interface with `encode` and `decode` methods that raise `NotImplementedError`s. `Aperture`, `Spider` and in future `Lens` and `Mirror` all implement the `Encodable` interface. Each concrete subclass then specifies its `encode` and `decode` behaviour and `decode_from_file` becomes,
```
for key in json_dict:
    try:
        layer = exec(f"{key}.decode({json_dict[key]})")
    catch NotImplementedError:
        # useful debugging message
```
Any thoughts?

**Comment by LouisDesdoigts** [comment]
I think this all looks good, I can't really say more without seeing an example of how you would use it though.

**Comment by Jordan-Dennis** [comment]
It is clear that we need a way to share the forwards model between people and devices. There was talk during the semester of serialising pre-built models using either `.json` or `.hdf5` files. 

The case for `.json`:
    > `.json` is very good (designed for) storing object 
      oriented classes.
    > `python` includes a `.json` processing tool in the 
      standard library which is not so bad. 
        > Works well with @LouisDesdoigts existing interface
          because it transforms the `.json` into a `dict`. 
        > We should be able to process the keys into a 
          `paths_dict` and then applying the updates is very 
          easy.
            > This raises the question of should we allow the 
              initialisation of systems directly via a 
              `paths_dict`.
            > There is always the option of adding keyword 
              arguments.
                > I find this messy and confusing if 
                  excessive.
                > There is the option for the 
                  `multipledispatch` package. This supports 
                  proper overloading, but it adds a 
                  dependancy since it is not part of the 
                  standard library. 

The case for `.hdf5`:
    > The `.hdf5` option is more useful for large arrays. 
        > I have already identified that the diffractive pupil 
          is likely to be one example where we will need this. 
        > I dislike `.hdf5` fileds because we will require 
          two different libraries to be added as dependencies 
          to use them. Namely `hdfdict` and `h5py`.
            > Strictly thinking I think that the first can 
              be avoided with a sneaky list comprehension but 
              it is not necessarily a good idea to do so. 
                > `hdfdict` is probably guards against edge 
                  cases much better. 
                > Things like corrupted files too large values 
                  ect. 

Are `.hdf5` and `.json` mutually exclusive/necessary at all? I do not think so. This means that we don't necessarily need to chose and could develop an interfaced that offered mixed functionality. Both `.hdf5` and `.json` have `dict` based interfaces. This brings up my earlier argument about initialisation via this method. 

To conclude, since there are a lot of `float`/`int` valued parameters and relatively few array valued ones `.json` makes more sense to me in the          general case. However, either option works. I believe that we want this functionality because it gives us a robust and streamlined way of sharing models, without just copy and pasting from each other code. This will prevent unnecessary code duplication and also the amount of boiler-plate within files working on the TOLIMAN mission, since the model will occupy its own file(s).

**Comment by Jordan-Dennis** [comment]
There are other options as well, such as storing the forwards model as a `dLux` object in its own file i.e. `toliman.py`. This could be part of the repository and imported through `dLux`. I am less favourable of this approach because `dLux` should in my eyes, be kept separate from the science that it is used for, but this opinion may not be shared.

**Comment by LouisDesdoigts** [comment]
Serialisation was implemented in Zodiax, no longer required here.
