### ISSUE TITLE
Improvements for Aperture

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#115]
The magnification is obsolete and does not provide any extra information. This is a reminder to myself to remove it at a later date.

**Comment by Jordan-Dennis** [comment]
Also I might split the hierarchy so that `RadiallySymmetricAperture` is a class. This would avoid applying null rotations to `CircularAperture` and `AnnularAperture` which happens at the moment.

**Comment by benjaminpope** [comment]
We probably don't want to be applying rotations to the arrays very often, for speed
