### ISSUE TITLE
Hierarchical Telescopes 

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#119]
Hi all,
Attempting to use gradient descent on a `CompoundAperture` has proved frustrating because it is difficult to specify global position parameters that apply to all the apertures and which have non-zero gradients. Note: You will need to be on the `Aperture` branch to use the code. I have posted the stack trace on the `Aperture` PR #114. I am able to work around this for now but I want to fix it before we complete #114.

I'm really not that sure where to begin with this other than using a `set_xxx` method in the global state that maintains this invariant. This will break the existing functionality in the `Base` class. Well not break but the `Base` functionality will not work on the `CompoundAperture` class.

If we want these two to work together then we will need to do quite a bit of work to make the `Base` extend to have `update_hierarchical_param` which I can see having the following method signature. 
```py
def _update_hierarchical_param(self, params_path: list, new_value):
```
This would update all the leaves in the `params_path` to the same `new_value`. There is also the issue of taking gradients with respect to the correct parameter (i.e. the whole aperture). Anyway, let me know your thoughts,

Regards

Jordan

**Comment by LouisDesdoigts** [comment]
This functionality already exists within the base class, you just need to specify multiple paths and a single value. Check out the nesting section of the pytree interface tutorial

**Comment by LouisDesdoigts** [comment]
This functionality already exists within the base class, you just need to specify multiple paths and a single value. Check out the nesting section of the pytree interface tutorial
