### ISSUE TITLE
`CreateWavefront.__call__` needs re-documenting.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#122]
Hi all, 
Something that I have noticed while working with the new apertures I wrote, is that since they do not store any coordinate information, when it comes time to plot them it is quite tricky to extract the coordinate information from the `Wavefront`/`OpticalSystem`. The only place I am aware of the coordinates is in the `Wavefront` but it is frustrating to get a hold of the `Wavefront` since it is not meant to be a part of the user API. While fiddling however, I often run into the following error,
![image](https://user-images.githubusercontent.com/93350879/192641099-d86d7ca8-8316-4dc6-90ba-7b7c7ecbf75c.png)
which, is why I'm not the biggest fan of the `params_dict`. At this point though I have accepted it and turned to the docs looking for what needs to be in `params_dict` and get the following,
![image](https://user-images.githubusercontent.com/93350879/192641273-47d3a723-faee-468e-8273-e90184852887.png)
When actually it needs, 
![image](https://user-images.githubusercontent.com/93350879/192641465-00e1b0ca-3515-470b-a12c-4b55c9f75405.png)
In general this is not such an issue we just need to make sure the docs are always kept up to date. I'm going to re-document the offending method now, but I think this issue is more important than the cause in this case. 

In general I think that we want to make sure that the users knows to use `dl.utils.get_pixel_coordinates` with the same values as the `CreateWavefront` as it will save them the frustration that I went through with this. Sorry if this is a bit of a rant, I didn't sleep too well last night so everything is annoying me today.

Regards

Jordan

**Comment by LouisDesdoigts** [comment]
@Jordan-Dennis it looks like you fixed this from the references to this issue, can this be closed or is there more to do?

**Comment by Jordan-Dennis** [comment]
Nah I was just leaving it open so that everyone got a chance to see it, because I thought it was important. I've close it now.

**Comment by Jordan-Dennis** [comment]
Some when this was reverted.

**Comment by LouisDesdoigts** [comment]
This was fixed with the implementation of the `.apply` method in the `OpticalLayer` class.
