### ISSUE TITLE
New `typing` Feature.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#132]
Hey @LouisDesdoigts,
I want to use a `typing` feature that we have not yet been using in `Basis`. Essentially I want to have `basis_funcs: List[callable]` which `typing` supports via `List` not `list` (notice the capital *L*). Just thought I would check this was OK since I did not see this feature in the `CONTRIBUTING.md`.

**Comment by LouisDesdoigts** [comment]
Yeah that should be fine, go for it 👍

**Comment by Jordan-Dennis** [comment]
Thanks :+1:
