### ISSUE TITLE
Style for Large List Comprehensions.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#133]
Sorry @LouisDesdoigts,
another style question. What happens when we have a long list comprehension. I have formatting these and they always end up looking gross. Shall we just enforce something like "break the line at `for`"?

Regards

Jordan

**Comment by LouisDesdoigts** [comment]
Yeah I'm don't think we need to enforce anything specific, I think just trying to put the line breaks where the code does different things (ie like at the for would be a good spot)

**Comment by Jordan-Dennis** [comment]
Cool thanks :+1:.
