### ISSUE TITLE
image header on docs page is broken

### ISSUE THREAD

**Issue by benjaminpope** [LouisDesdoigts/dLux#137]
just reads 'alt text'

**Comment by LouisDesdoigts** [comment]
Yeah I've seen that before, I have no idea what is causing it though. Any ideas?

**Comment by benjaminpope** [comment]
Should just be the path to the image is wrong. Can check this interactively with `mkdocs serve`.

**Comment by LouisDesdoigts** [comment]
Yep had the docs/ at the start but mkdocs works from that folder - fixed now
