### ISSUE TITLE
Inherit Documentation.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#138]
Hi all,
Perhaps this is just me, but as I write new classes I tend to re-document parameters from classes higher in the hierarchy. This is mainly so that `help(ClassName)` provides the correct documentation. I have noticed that this swells the number of lines of code vastly and there is a lot of repetition. 

Firstly, I am curious if you think that the DRY principle should also apply to comments. I think that it should. I believe that the DRY principle should apply because if we decide to remove/change a parameter higher in the hierarchy then the documentation of the inheriting classes now also needs to be updated leading to more work.

To the best of my knowledge, there does not exist any succinct way to inherit documentation, because vanilla python does not persist class variables explicitly. However, through some clever use of dunder methods like `__annotations__` we should be able to cobble something together. Do you think that this is worth the effort?

Regards

Jordan

**Comment by Jordan-Dennis** [comment]
(An interesting)[https://stackoverflow.com/questions/2025562/inherit-docstrings-in-python-class-inheritance] example of a community effort.

**Comment by ataras2** [comment]
I'm not sure this _needs_ a in code solution (though that would be cleaner for both docs and code readers). Another option is to have the documentation from code generate this in a way that makes it clear what the classes derive from, and point users to base class in the same page or through a link.

**Comment by ataras2** [comment]
[This example](https://stackoverflow.com/questions/17393176/python-3-method-docstring-inheritance-without-breaking-decorators-or-violating) also seems relevant

**Comment by Jordan-Dennis** [comment]
Yeah I agree. Originally, I was just documenting what was new in the child, but it meant that it could be hard to tell what the parameters were called and what they did. I wrote the code in question so I imagine it would have been harder for other people, especially if they did not have a strong mastery of the non-pythonic OOP that we are using.

**Comment by LouisDesdoigts** [comment]
Yeah I completely agree, the docs are annoying because of the complex class inheritance in a lot of places and is prone to mistakes if upstream changes are made. Am open to suggestions, will keep an eye on this issue if you want to post suggestions and ideas!

**Comment by LouisDesdoigts** [comment]
We also have the issue of lines from the constructor appearing in the docs (see https://louisdesdoigts.github.io/dLux/core/optics/) ` layers = dLux.utils.list_to_dictionary(layers) instance-attribute`.

**Comment by Jordan-Dennis** [comment]
A simple way of replicating this that is plagued with downsides would be defining *documentation* **templates**. These are the bits that you *copy-paste* for each new function/class. For example, in the testing code it would be:
```py
test_doc_template: str = """
Returns:
--------
{}: callable
    A function that has all keyword arguments and can be
    used to create a `{}` layer for testing.
"""
```
where you could then have a decorator to set the documentation for the function. 
```py
@set_doc_from_template(test_doc_template, "_create_aperture", "Aperture")
def create_aperture() -> callable: 
```
The downsides of this are numerous, but I thought it was an interesting concept. In-particular you can add strings in python so it might be that,
```py
some_doc_template: str = """
Parameters:
-----------
Lots of parameters
"""

down_stream_doc_template = some_doc_template + """
more parameters
"""
```
This means that upstream changes still affect downstream.

**Comment by Jordan-Dennis** [comment]
I've been thinking about this and I think I have a nice solution in mind. My idea is to do some meta-programming, i.e. write a program to pass our files and automatically format our docs in the way we chose. What do you think @LouisDesdoigts and @atras2?

**Comment by benjaminpope** [comment]
Yeah I think we will not be able to replicate or beat the functionality in MkDocs, Quarto, ReadTheDocs or any of the other fully featured packages for documentation management. Nevertheless, at lowish priority, it is worth investigating (and fixing?) the bad propagation of equinox module attributes into the docs, which we have discussed with Kidger.

———————————————
Dr Benjamin Pope (he/him)
Lecturer in Astrophysics
University of Queensland
benjaminpope.github.io
________________________________

**Comment by Jordan-Dennis** [comment]
I did not mean anything as complex as the ideas you guys are bandying. This program would just visit each class and check that it shared the same documentation as the parent class for the same parameters and if not raise a warning. If the documentation was absent it could simply copy it in place.

**Comment by Jordan-Dennis** [comment]
So I have thoroughly investigated this for the toliman forwards model. It turns out that `pytkdocs`, which is used by `mkdocs-python-legacy` allows this, but `pytkdocs` caused all sorts of other trouble with the rendering of `numpy` style docstrings. Instead I had to format the docstrings according to the google style, which would create a lot of work. Additionally, `pytkdocs` is having a replacement built and in general the code is *legacy* meaning it is not well maintained. We know how to do this now for furhter reference.
