### ISSUE TITLE
Soft pixels in hard mode.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#142]
Where identically zero is encounted a pixel with a value of `.5` can arise even when operating in hard mode. I think that we need to go back to separate calculation of the hard aperture and an `if` statement to differentiate the pair. This will be faster when operating in hard mode. Moreover, the softening is quite complex, so this will improve the readability of the code.

**Comment by LouisDesdoigts** [comment]
Yeah might be better to move to a if statement, otherwise its probably fine to just add a floor or ceil call to these. They aren't runtime generated so its not a huge issue.
