### ISSUE TITLE
Add initialisation tests.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#143]
My idea is: we add a test file that only tries to import `dLux`. I believe that this is worth doing because it will simplify the output of the automated tests, which we can set to stop running if this fails.

**Comment by Jordan-Dennis** [comment]
I have achieved this, but the tests are designed to run on `linux` and it will raise an error if the device is not `linux`. I figured this was OK since it is mainly to halt the automated testing if these tests fail. The only reason that this is specific to `linux` is that it uses `rm -r`. We could remove this and then it would be fine. @LouisDesdoigts I'm tagging you for an opinion.

**Comment by LouisDesdoigts** [comment]
The test should run on all Unix system by default (same as Jax) and have been running on my Mac. Where is this `rm -r` command?

**Comment by Jordan-Dennis** [comment]
It is in the `test_initialisation.py` file at the very bottom. It is just cleaning up the `dLux.egg-info` and `build` dirs.

**Comment by LouisDesdoigts** [comment]
Where is the `test_initialisation.py` file? I can't seem to find it

**Comment by Jordan-Dennis** [comment]
It should be in the `wavefront-tests` branch.
