### ISSUE TITLE
Depreciate `Utitlity` for `pytest.fixture`.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#144]
The pytest fixture allows one to define utilities without the baggage that I created. The basic syntax for use is:
```python
import pytest

@pytest.fixture
def example_dLux_layer():
    # Construct a layer here.
    return layer



def test_dLux_layer(fixture: callable) -> None:
    layer: Layer = fixture
    # Do tests

```

**Comment by LouisDesdoigts** [comment]
This looks like it would be better in the long run. I would probably leave this for now and we can dev it on a separate branch after the Apertures merge, unless you're already using it on that branch in which case we should do the whole thing on there - Thoughts?

**Comment by Jordan-Dennis** [comment]
I think this will be quick. The syntax is nearly the same, so I might make it part of the `apertures` pull request.

**Comment by LouisDesdoigts** [comment]
Yep cool, am on board with this

**Comment by ataras2** [comment]
Agreed with changing now for apertures tests too

**Comment by Jordan-Dennis** [comment]
[This](https://docs.pytest.org/en/latest/how-to/parametrize.html#parametrize-basics) is more involved than I thought. @ataras2 have you got parameters passing into fixtures yet?

**Comment by Jordan-Dennis** [comment]
`pytest` has some pretty lit features actually. For example, you can run tests using `-k` to search for keywords. 
```bash
pytest -k "CartesianWavefront" tests/test_wavefronts.py
```
