### ISSUE TITLE
Define Types Once

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#147]
Hi all, 
it might be nice if we had a small script that defined all of our types, which we could then import as necessary into our other files. This would reduce the amount of boilerplate at the top of many files which have things like . Here is an example which I have not tested:
```python
__all__ = [OpticalLayer, ApertureLayer, WavefrontLayer, Array]
Array = np.ndarray
WavefrontLayer = dLux.wavefronts.WavefrontLayer
ApertureLayer = dLux.apertures.ApertureLayer
OpticalLayer = dLux.optics.OpticalLayer
```
What are your thoughts?

**Comment by LouisDesdoigts** [comment]
Hmm I see the point but I think this hurts us on the readability front. Having delved deep into the source code of quite a few different packages, being more explicit rather than clever has always been a top priority. Given that this is only a few lines of code and they aren't repeated within any of the scripts, then I think they should be done explicitly within that script.

**Comment by LouisDesdoigts** [comment]
I also have never been able to get the `OpticalLayer = dLux.optics.OpticalLayer` to work without throwing an error on importiirc).

**Comment by ataras2** [comment]
I think keeping `Layer` objects explicitly defined is not a bad thing. For things like `Array` I'm less sure, and as Louis said the repetition is once as part of the structure of a file.

**Comment by Jordan-Dennis** [comment]
Because type annotations are *optional* in python the exact **implementation** of the type does not matter. We have already encountered problems across the different files with how types have been handled. For example, changing from `Array = TypeVar("Array")` to `Array = np.ndarray`. Other examples include the `Wavefront` type, which is included in most `__call__` methods. It is just more work to change this across multiple files (anti-DRY).

Since, the package is nearly stable I don't think it will matter too much anyway :shrug:, so I will close the issue.
