### ISSUE TITLE
Test Documentation

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#148]
Hi all,
I was wondering where we should document our testing practices. In particular I think that we should document how we are using `pytest`; for example, our naming conventions for fixtures ect.

**Comment by ataras2** [comment]
This sounds good. Explicit pointers in the docs to `conftest.py` can show how to instantiate classes with "typical" values, and the `test_*.py` show how to use the classes on top of the tute notebooks.

**Comment by Jordan-Dennis** [comment]
I think that this belongs in `CONTRIBUTING.md` does anyone have any other thoughts. Here is a draft paragraph:
> ## Tests
> When adding features or extending functionality, robustness is important. To verify that your code is robust, please implement thorough unit tests obey the FIRST and AAAC principles. FIRST stands for *f*ast, *i*ndependent, *re*peatable, *s*elf-validating and *t*horough whereas AAAC represents *a*rrange, *a*ct, *a*ssert and *c*lean-up. The simplest way to implement tests is using `pytest.fixture`s, which are stored in `tests/conftest.py`. This covers the *arrange* and *clean-up* phases of a test. Moreover,  `fixtures` are cached making them *fast* and (circumstantially) *independent*. Please test each public method.
What do you think?
Regards
Jordan.

**Comment by LouisDesdoigts** [comment]
Covered in CONTRIBUTING.md
