### ISSUE TITLE
More Plotting Utilities.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#158]
Hi all, 
This is a personal reminder to move the functions I have been using to generate test plots of the apertures and basis into \`utils\`. Given \#157 I think that it would even make sense to move \`plotting.py\` outside of the \`utils\` directory if it does get fractured. What are your thoughts on this. For \#157 I think that \`utils\` should only contain functions completely decoupled from \`dLux\`.

**Comment by LouisDesdoigts** [comment]
Plotting utilities have been decided against package wide.
