### ISSUE TITLE
Dimensionality Tests as a Function.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#159]
Hi all,
based on the content of #146, I think that we should create functions to test dimensionality. Even if this is a one line function it would make sure that error messages were consistent when parameters with the incorrect shape were provided. I see this as taking three arguments, the parameter name, the value that is being initialised and the correct dimensions. Here is a simple example of the API,
```python 
>>> validate_attr_shape("coefficients", np.ones((6, 3, 3)), (6, 1))
>>> AssertionError: Atrribute "coefficients" of "AberratedAperture" should have did not have consistent dimensions. I was expecting "(6, 1)" but got "(6, 3, 3)".
```
Regards
Jordan

**Comment by LouisDesdoigts** [comment]
Yep I think this is a good choice, will expand this to a lot of the other tests in the package in the long run.

**Comment by Jordan-Dennis** [comment]
This was implemented, as far as I am aware. Hence I am closing the issue.
