### ISSUE TITLE
Raise `ValueError` Instead of using `assert`.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#160]
Hi all,
`assert` is specifically designed for debugging purposes. If we want to include defensive programming in the constructors then I think that we should raise `ValueError`s or even create our own custom error classes. For example, we could create an error `InconsistentDimensionsError` or `PyTreeError`. This is quite simple and I believe that you just have to inherit from `Excepetion` when creating a class. 
```python 
class PyTreeError(Exception):
    def __init__(self, pytree, message):
        super().__init__(message)
```
If we decide to make custom exceptions (like this) then I think we should try and keep them as general as possible. For example, I do **not** think it would be a good idea to have errors like `InvalidAbebrratedApertureCoeffsError:` or `CreateWavefrontInvalidTypeError:`. For this reason I lean more toward using `ValueError` most of the time with perhaps some specialised errors where a specific message with differently formated arguments is going to be used. This ties into #159 and can replace the ideas discussed in #159 or be used in conjunction with #159 to guarantee consistent formatting of error messages without making custom exceptions.
Regards
Jordan

**Comment by LouisDesdoigts** [comment]
Done in 0.13
