### ISSUE TITLE
Are `pytest` `fixture`s needed for the `ApertureLayer` classes. 

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#167]
Hi all,
I originally discovered `pytest` `fixture`s working with the aperture testing because there were lots of parameters that did not have default values. Now almost all the parameters have a default value meaning that the way we have implemented our fixtures does very little to help. @ataras2 and I put in a huge effort to update the testing with our new knowledge of `pytest` but I think that we may have overcooked it slightly (used `fixture`s where they were not needed). I think we need to discuss how we do the tests efficiently now that we understand better how `pytest` works. 

Regards

Jordan

**Comment by LouisDesdoigts** [comment]
This has been resolved in 0.13, with fixtures being used in the `conftest.py` for class constructor.
