### ISSUE TITLE
Depreciate Orthonormalisation.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#174]
Hi all,
Ben's probably shaking his head at this one. The orthonormalisation is only significant once you include a certain number of zernike terms. I do not want the program to waste time on it if then number of terms is less than this threshold, but I also don't want to pixk a threshold as that is quite arbitrary. Instead I think that we depreciate this functionality and instead just cookie cutter the basis functions on the aperture. 
What are your thoughts 
Jordan

**Comment by LouisDesdoigts** [comment]
Aaah Ben is always right 😉

For the irregular shapes I would just go with cookie-cutter. Maybe just put the orthonormalisation code somewhere in utils, no need to remove functionality if it is already built!

**Comment by LouisDesdoigts** [comment]
This is still good functionality that can be used, lets keep it!
