### ISSUE TITLE
Profiling on GPU.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#179]
Hi all, 
As I strive to make my forwards models faster I am finding results that are counter-intuitive. For example, a vectorised version running slower than a non-vectorised version. I am starting to wonder if this is a CPU thing so I would like to do some testing on GPU. 
Hit me up if you have a free GPU to run some code. 
Regards
Jordan.

**Comment by benjaminpope** [comment]
We have GPUs at SMP, or you can try Colab (but it will only work in 32 bit).

———————————————
Dr Benjamin Pope (he/him)
Lecturer in Astrophysics
University of Queensland
benjaminpope.github.io
________________________________
From: Jordan Dennis ***@***.***>
Sent: Thursday, January 5, 2023 10:50:28 AM
To: LouisDesdoigts/dLux ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LouisDesdoigts/dLux] Profiling on GPU. (Issue #179)


Hi all,
As I strive to make my forwards models faster I am finding results that are counter-intuitive. For example, a vectorised version running slower than a non-vectorised version. I am starting to wonder if this is a CPU thing so I would like to do some testing on GPU.
Hit me up if you have a free GPU to run some code.
Regards
Jordan.

**Comment by LouisDesdoigts** [comment]
Colab is probably the easiest, but comparing performance across different hardware is kind of apples to oranges... 

I'm a little suspicious that a vectorised version is running slower though, where is this in the code?

**Comment by Jordan-Dennis** [comment]
Here are two implementations, 
```python 
@ft.partial(jax.jit, inline=True)
def soft_square_aperture(width: float, ccoords: float) -> float:
    pixel_scale: float = get_pixel_scale(ccoords)
    acoords: float = jax.lax.abs(ccoords)
    x: float = jax.lax.index_in_dim(acoords, 0)
    y: float = jax.lax.index_in_dim(acoords, 1)
    square: float = ((x < width) & (y < width)).astype(float)
    edges: float = ((x < (width + pixel_scale)) & (y < (width + pixel_scale))).astype(float)
    return ((square + edges) / 2.).squeeze()

@ft.partial(jax.jit, inline=True)
def _soft_square_aperture(width: float, ccoords: float) -> float:
    pixel_scale: float = get_pixel_scale(ccoords)
    acoords: float = jax.lax.abs(ccoords)
    square: float = (acoords < width).prod(axis = 0).astype(float)
    edges: float = (acoords < (width + pixel_scale)).prod(axis = 0).astype(float)
    return (square + edges) / 2.
```
Running this on my machine I find that,
![image](https://user-images.githubusercontent.com/93350879/210703572-69881078-0630-45bb-ad38-55f1a3e09b97.png)
Which is nearly a factor of ten.

**Comment by Jordan-Dennis** [comment]
Similar results on colab
![image](https://user-images.githubusercontent.com/93350879/210704419-3a78a8ed-7f41-44e9-9132-7b573e4fc393.png)

**Comment by Jordan-Dennis** [comment]
The vectorisation thing seems to be really prevalent. Here is another example with similar results,
```python
import jax 

@jax.jit
def hypotenuse_v0(coords: float) -> float:
    return jax.lax.sqrt(jax.lax.integer_pow(coords, 2).sum(axis = 0))

@jax.jit
def hypotenuse_v1(ccoords: float) -> float:
    x: float = ccoords[0]
    y: float = ccoords[1]
    return np.hypot(x, y)

@jax.jit
def hypotenuse_v2(ccoords: float) -> float:
    x: float = ccoords[0]
    y: float = ccoords[1]
    x_sq: float = jax.lax.integer_pow(x, 2)
    y_sq: float = jax.lax.integer_pow(y, 2)
    return jax.lax.sqrt(x_sq + y_sq)

@jax.jit
def hypotenuse_v3(ccoords: float) -> float:
    x: float = jax.lax.index_in_dim(ccoords, 0)
    y: float = jax.lax.index_in_dim(ccoords, 1)
    x_sq: float = jax.lax.integer_pow(x, 2)
    y_sq: float = jax.lax.integer_pow(y, 2)
    return jax.lax.sqrt(x_sq + y_sq)

%%timeit
hypotenuse_v0(ccoords)

%%timeit
hypotenuse_v1(ccoords)

%%timeit
hypotenuse_v2(ccoords)

%%timeit
hypotenuse_v3(ccoords)
```
The builtin version as a benchmark showed similar performance to `v2` and `v3`. The builtin version actually checks for zeros to avoid calling `integer_pow` on them. This is all really confusing me and I am thinking that I might make a `jax` issue since it is very counter intuitive.

**Comment by Jordan-Dennis** [comment]
Yes mostly. I often forget it the first time though.

**Comment by Jordan-Dennis** [comment]
Here is my times,
![image](https://user-images.githubusercontent.com/93350879/210897474-02fc0eee-c1bd-45da-a6a5-fa439e910f17.png)
You can see it is a significant difference. What's more is the `jaxpr` looks really nice for `v0` at just three lines. Many less than the others.

**Comment by Jordan-Dennis** [comment]
So @jakevdp ran my code on a GPU and they all had very similar performance. He implied that `XLA` compiler has seen a lot more work on GPU than on CPU. @benjaminpope is there any chance I can use some of the SMP GPUs (or just send the code to you)?

**Comment by LouisDesdoigts** [comment]
Honestly it colab would be the quickest and easiest

**Comment by Jordan-Dennis** [comment]
Last time I tried `colab` I got the same results, but that might have been instance specific.

> Similar results on colab ![image](https://user-images.githubusercontent.com/93350879/210704419-3a78a8ed-7f41-44e9-9132-7b573e4fc393.png)

**Comment by LouisDesdoigts** [comment]
Colab CPU:

<img width="707" alt="Screen Shot 2023-01-06 at 11 31 28 am" src="https://user-images.githubusercontent.com/42196907/210905794-fd380f1b-cc63-41f2-8211-b3ae12a143cb.png">

Colab GPU:

<img width="718" alt="Screen Shot 2023-01-06 at 11 32 50 am" src="https://user-images.githubusercontent.com/42196907/210905825-e61d1cc7-846e-4e61-9c01-0978d29df91f.png">

**Comment by LouisDesdoigts** [comment]
Relative times appear the same

**Comment by Jordan-Dennis** [comment]
I musn't have set up `COLAB` correctly. I'll look into it a bit more since I don't normally use it.
