### ISSUE TITLE
`if` Statements Behave Differently in `jax==0.4.1`

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#182]
Hi all,
`if` statements no longer seem to be compilable (at all) in the latest `jax`. I think any run-time if statements (there aren't many) need to be moved over to `cond`.
Regards
Jordan

**Comment by LouisDesdoigts** [comment]
I can't see anything in the changelog, what exactly is the different behavior? Using `cond` with python booleans breaks some things so id be surprised if this was the case

**Comment by Jordan-Dennis** [comment]
Wasn't sure the issue popped up and disappeared. I don't know what caused it. I think it might have been something persisting in the `ipykernel`, that wasn't meant to be there.
