### ISSUE TITLE
Add Links to Examples in API Docs.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#188]
Hi all,
I think it might be useful to add links in the API docs (i.e. the docstrings) to examples in the tutorials. I am finding that the doc strings themselves are often not enough to go by and a few simple examples would go a long way to clarifying how to use the various classes. If we did not want to set up links we could just add examples to the doc strings.
Regards
Jordan

**Comment by LouisDesdoigts** [comment]
Yeah I do want to try and expands the docs in general with minimal examples, I figured this would be a part of the process of making the beginner ∂Lux overview tutorials.

**Comment by LouisDesdoigts** [comment]
Done with PR #218
