### ISSUE TITLE
Implement `Extendable` Interface.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#189]
Hi all,
when coding pre-built forwards models there is the requirement that the user be able to `.insert` and `.remove` layers from the optics/detector/scene. I think that the most idiomatic way would be to extend `ExtendedBase` into `ExtendableModule`/`ExtendableBase` (confusing name) or to create a separate interface and use multiple inheritance.

What are your thoughts?

Jordan

**Comment by LouisDesdoigts** [comment]
Not sure this would really fit as an extension of Zodiax classes. This functionality should be pretty easy to build by iterating through the stored dictionaries and inserting/replacing as appropriate and re-calling the constructor of the class. Can be done manually at present without much effort though.

**Comment by Jordan-Dennis** [comment]
![image](https://user-images.githubusercontent.com/93350879/212218507-76347a6c-27dd-4170-9346-5ec00341e20d.png)
This was my attempt, and similar for the `.remove` method. I haven't tested them though.

**Comment by LouisDesdoigts** [comment]
Not sure if that will mesh exactly right with the OrderedDict. Also this could lead to namespace overlap if that type of layer already exists within the dictionary. I would basically do this but decompose the dictionary to a list, insert to the list and re-call the list_to_dict function and then update. I can't see this being a differentiable operation, or needing to be.
