### ISSUE TITLE
Build code to port poppy models

### ISSUE THREAD

**Issue by LouisDesdoigts** [LouisDesdoigts/dLux#2]

**Comment by Jordan-Dennis** [comment]
Sounds lit. I've already looked into this a little and found that the `inspect` library provided some useful functionality, with the `settrace` function and `source` (for more hardcore interpreter style). It might also be possible to do this directly in `jax` using `Tracer` classes, but that would be more work with little to no upside.

**Comment by LouisDesdoigts** [comment]
This has been decided against since the frameworks are too different.
