### ISSUE TITLE
Position in binary is not flux weighted

### ISSUE THREAD

**Issue by benjaminpope** [LouisDesdoigts/dLux#243]
AFAICT where we define the positions of binary sources, this is just a relative position to a geometric centre - but it is usually more important to define positions relative to the _flux_ centre. https://github.com/LouisDesdoigts/dLux/blob/518ea5249d90d26ac3fc6179e6c0f2d4b4879b5d/dLux/sources.py#L286

**Comment by LouisDesdoigts** [comment]
Yeah that is correct.... however I really dislike this idea 😅

**Comment by LouisDesdoigts** [comment]
Decided against this one. Closing for now, can always be made into a new class later.
