### ISSUE TITLE
ConcretizationTypeError in nd_coords

### ISSUE THREAD

**Issue by maxecharles** [LouisDesdoigts/dLux#260]
I'm trying to implement a class that uses `jax.lax.cond` such that I can use conditional statements under `jit`. My class calls the `nd_coords` function and gives this error:

```bash
ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: traced array with shape int64[].
It arose in the jnp.arange argument 'stop'
The error occurred while tracing the function <lambda> at [/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/dLuxToliman/layers/detector_layers.py:309](https://file+.vscode-resource.vscode-cdn.net/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/dLuxToliman/layers/detector_layers.py:309) for cond. This value became a tracer due to JAX operations on these lines:
```

It's erroring out in the `pixel_fn` defined within `nd_coords` which looks like:

```python
def pixel_fn(n, offset, scale):
    # TODO: calculate the start and end points first and then use linspace
    # so that ops are done on floats not arrays
    # scale = diam / n
    pix = np.arange(n) - (n - 1) / 2.0
    pix *= scale
    pix -= offset
    return pix
```

**Comment by maxecharles** [comment]
I rewrote the function according to the TODO and committed it to the `coord-concrete` branch (97a05bec3aba3a539cffb99a6b145d93e59815dd). It now looks like:

```python
def pixel_fn(n, offset, scale):
    start = -(n - 1) / 2 * scale - offset
    end = (n - 1) / 2 * scale - offset
    return np.linspace(start, end, n)
```

This obviously gives essentially the same error:

```bash
ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: traced array with shape int64[].
'num' argument of jnp.linspace
The error occurred while tracing the function <lambda> at [/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/dLuxToliman/layers/detector_layers.py:309](https://file+.vscode-resource.vscode-cdn.net/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/dLuxToliman/layers/detector_layers.py:309) for cond. This value became a tracer due to JAX operations on these lines:
...
```

Anyway my understanding is that it doesn't like `n` because it could take on any value and `jax` doesn't like that? Is there a way around this / is this actually a problem or am I just silly for wanting to use `jax.lax.cond` in the first place. ...

**Comment by LouisDesdoigts** [comment]
This pixel coords function is called many many times throughout dLux under jit, I suspect it's the formulation of the function you're using that is generating the value n conditionally on some traced value, hence the error. Can you give a full mwe of this error including how you're using lax.cond? It has some extra constraints that could be giving rise to this

**Comment by maxecharles** [comment]
Basically I'm trying to generate a convolution kernel where the kernel size is determined by the jitter parameter `A` in the `kernel_size` method. Kernel size is restricted to odd integers.
However I don't want to generate a kernel size of 1 as that leads to yucky issues. So essentially I had
```python
def generate_kernel(self, pixel_scale: float) -> Array:
    if self.kernel_size == 1:
        return np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]])
    else:
        ... generate the kernel normally ...
```
Which kinda needs a conditional there. So this is the class in it's current state which is me trying to get around that:

```python
class SHMJitter(BaseJitter):

    A: float
    phi: float

    def __init__(
        self: DetectorLayer,
        A: float,  # amplitude in arcseconds
        phi: float,  # angle
    ):
        # setting parameters
        self.A = A
        self.phi = phi

        # calling parent constructor
        super().__init__()

    def kernel_size(self, pixel_scale: float) -> int:

        kernel_size = np.ceil(2 * self.A / pixel_scale).astype(int)
        kernel_size += 1 - kernel_size % 2  # ensuring odd integer

        return kernel_size
    
    @staticmethod
    def delta_kernel(pixel_scale: None) -> Array:
        return np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]])
    
    def extended_kernel(self, pixel_scale: float) -> Array:
        ... generate kernel the normal way using self.A ...
        return kernel / np.sum(kernel)

    def generate_kernel(self, pixel_scale: float) -> Array:

        # checking for if kernel is a single pixel
        # in which case just return a delta function
        return jax.lax.cond(
            self.kernel_size(pixel_scale) == 1,
            lambda: self.delta_kernel(pixel_scale),
            lambda: self.extended_kernel(pixel_scale),
        )
```

**Comment by LouisDesdoigts** [comment]
Okay yep so this isn't going to work no matter which way you slice it. The kernel size parameter (even though it's an int) is determined by pixel scale which is a tracer -> therefore kernel size will _always_ be a tracer and can't be used as a shape parameter. This is a consequence of XLA requiring static array sizes, there's no fancy footwork with the code that you can do that will fix this. 

Because of this limitation, easiest way around this is probably just making kernel size an attribute of the class. Not an ideal solution but there is simply no way to compile a function with dynamic arrays sizes to XLA no matter how hard you try.

**Comment by maxecharles** [comment]
:(
