### ISSUE TITLE
Github Pages inconsistent with latest docs

### ISSUE THREAD

**Issue by h-greer** [LouisDesdoigts/dLux#270]
It looks like the latest docs updates from #267 haven't made it on to the Github Pages (but all the previous docs updates e.g. #263 have worked).  I haven't found any cause yet - it builds fine on my machine and the output of the failing docs check from #267 has expired so I can't inspect it.  I'll probably have some documentation fixes in the next few days, perhaps those will trigger it again and we can get a better idea of the cause.

**Comment by LouisDesdoigts** [comment]
Yeah that last docs build failed for an unknown and opaque reason. In my experience sometimes it build locally and then fails on github, only to work again on the next run without any changes. Unfortunately there's no simple way to test a docs build on other branches that I have found, so my plan was just to wait for the next PR. I also never realised the logs expire, that's quite interesting! 

I'd be very happy to accept any PR's on the docs, I'm uniquely gifted at missing spelling and grammatical errors!
