### ISSUE TITLE
Logical Cohesion of `Layer` Objects

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#39]
I was indexing the `layers.py` file and noticed that we had both `ApplyBasicOPD` and `ApplyOPD`. I was wondering if we could amalgamate (that's a lot of a's) both of these into a `WavePlate`/`PhasePlate` class. The functionality of the call method is similar, one adding a scalar the other an array. By no means an important or necessary change, I think it would help the code match to tangible objects although it may not be possible.

Let me know what you think.

**Comment by LouisDesdoigts** [comment]
Ah yeah so its actually `ApplyBasisOPD`, not basic. These classes are logically distinct, with `ApplyOPD` allowing both scalar and array input, letting us apply things like etched masks. The `ApplyBasisOPD` takes in a set of basis vectors (eg zernikes, hexikies) and coefficients, allowing for parameterised inputs. 98% of the time `ApplyBasisOPD` is a glorified `ApplyZernike` function, just a bit more general.

I am open to potentially restructuring these if there is a compelling reason to, at the moment I've opted for generality and flexibility.

**Comment by Jordan-Dennis** [comment]
Ahh I clearly didn't read that correctly. I'll close this issue, since I thought they were much more similar.
