### ISSUE TITLE
Restrucutre /src

### ISSUE THREAD

**Issue by LouisDesdoigts** [LouisDesdoigts/dLux#58]
So the /src folder is getting a bit unwieldy. I propose we create a sub-directory called `extras` or something to store the non-core functionality scripts.

The idea would be the scripts recently moved into /src such as `bayes.py`, `helpers.py`, `plotting.py` would live in /extras as a collection of scripts that are designed to work with ∂lux but are not core and therefore not documented or tested.

Over time some of this functionality would be lifted to /src, such as a subset of the `helpers.py` functions as they are widely applicable to the usage of the package.

This could also be a good place to put a `development.py` script to place layers in development (ie not documented and tested) so that we can all have access and use consistent versions. This would be very useful for the development of the JWST models so we can put code to share without while still being flexible.

**Comment by Jordan-Dennis** [comment]
I agree, we should implement some set of sub-modules. Personally I quite like the following structure:
```
src/
    optics/
        wavefronts.py
        layers.py
        base.py
    statistics/
        bayes.py
        helpers.py?
    graphics/
        plotting.py
```
As this groups things by the functionality that they add. We would have to change the init file to:
```
from . import optics
from . import statistics
from . import graphics
```
So the import in scripts would becomes `from dLux.optics import *`

**Comment by Jordan-Dennis** [comment]
So I have implemented the structure I described above on the `HexagonsAndHexikes` branch as a demo/example. I added a `src/dev/development.py` as well based on @LouisDesdoigts's suggestion. I think having a `dev` directory even might be good because then you can have multiple files.

**Comment by Jordan-Dennis** [comment]
To keep everyone in the loop this was actually much harder than expected but I have it working on the `HexagonsAndHexikes` branch. The way it works is `src` now looks like this:
```
src/
    dLux/
        __init__.py
        optics/
            __init__.py
            base.py
            wavefronts.py
            propagators.py
            layers.py
        graphics/
            __init__.py
            plotting.py
        statistics/
            __init__.py
            zernike.py
            hexikes.py
            bayes.py
        utilities/
            __init__.py
            helpers.py
            models.py
        dev/
            development.py
```
I'm not particularly attached to this exact structure and there are many that work. The important thing is we know how to implement this. I think other structures like `dLux.optics` and `dLux.utils` been simpler and easier to use. Please respond @LouisDesdoigts and @atras2 if there are particular configurations that you want to trial. For now I will leave it as is.

**Comment by Jordan-Dennis** [comment]
As a reference for any who are interested the relevant websites is:
https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
which had a very useful guide once I took the time to read it thoroughly

**Comment by LouisDesdoigts** [comment]
Yeah so really there is a lot of overlap with all of these scripts and directories, I think any structure will ultimately be somewhat arbitrary. I think it might be work keeping the 'core' functionality directly in the /src (or /dLux) folders, and only having a /utils and /dev directories, maybe with a /models too.

```
dLux/
    __init__.py
    base.py
    wavefronts.py
    propagators.py
    layers.py
    coordinates.py # For paraxial coordinate grids
    transforms.py # For arcsec_to_radians, cart_to_polar, etc
    utilities/
        __init__.py
        helpers.py
        models.py
        zernike.py
        bayes.py
        plotting.py
    dev/
        development.py
        hexikes.py
```

This structure makes sense to me, letting us add any specific directories once there is enough of a code base to warrant it (ie splitting off into /models once we have integrated the code for making the JWST models). Let me know what you think.

**Comment by Jordan-Dennis** [comment]
That looks perfect. I will change the structure on the `HexagonsAndHexikes` branch. A little bit of warning, this mixes namespace packages and normal packages. I think I know how to deal with it but it might become:
```py
src/
    __init__.py
    dLux/
        __init__.py
        base.py
        wavefronts.py
        propagators.py
        layers.py
        coordinates.py # For paraxial coordinate grids
        transforms.py # For arcsec_to_radians, cart_to_polar, etc
    utilities/
        __init__.py
        helpers.py
        models.py
        zernike.py
        bayes.py
        plotting.py
    dev/
        development.py
        hexikes.py
```
where the top level `__ init __` file will let us import it in the same structure @LouisDesdoigts described. I will have a fiddle and hopefully it just works out of the box though.

**Comment by Jordan-Dennis** [comment]
So the extra `dLux` directory seems to be a requirement for `setuptools`. As an informal reference checkout (this)[https://stackoverflow.com/questions/59543313/pip-install-error-package-directory-does-not-exist] stack post.

**Comment by Jordan-Dennis** [comment]
This is now resolved. To clarify the changes:
 - `src` -> `dLux` to avoid `pip` calling the package `src`. `poppy` has a similar structure.
 - `packages=["dLux", "dLux/utils"]`; the packages are manually entered. 
 - `__init__.py`; all functions are manually imported e.g. `from .wavefronts import GaussianWavefront`. This means if you add a function or class it also needs to be added to the `__init__.py`.

**Comment by LouisDesdoigts** [comment]
Cheers Jordan, this is great stuff.  

> __init__.py; all functions are manually imported e.g. from .wavefronts import GaussianWavefront. This means if you add a function or class it also needs to be added to the __init__.py.

Just curious, is this a necessary change to allow the new structure or just a 'best practice' sort of this?
