### ISSUE TITLE
Add GoogleColab set up to docs

### ISSUE THREAD

**Issue by LouisDesdoigts** [LouisDesdoigts/dLux#61]
## Windows/Google Colab Quickstart
`jaxlib` can be problematic on windows so we suggest users run our library on [Google Colab](https://research.google.com/colaboratory/).
There are a few extra steps to get setup
1. At the top of each colab file you will need 
``` 
!git clone https://github.com/LouisDesdoigts/dLux.git # Download latest version
!cd dLux; pip install . # Navigate to ∂Lux and install from source
!pip install latex # Not needed, but just to make plots nicer
!apt install texlive texlive-latex-extra texlive-fonts-recommended dvipng cm-super
``` 
2. If you are using a notebook from our tutorials, you should add the notebooks folder to the path for imports to work
```
import sys
sys.path.insert(0,  './dLux/notebooks')
```
​
**Tips and Tricks**
- You can read/write data from your own drive using
```
from google.colab import drive
drive.mount('/content/drive')
```
- View the files using the left sidebar to navigate

**Comment by ataras2** [comment]
Addition to Tips and Tricks: Colab GPU works with the notebooks as is, you just have to change the Runtime mode

**Comment by ataras2** [comment]
Further notes (might belong outside a quick start guide):
- Colab runs on 3.7 at the moment, while some parts of feautre branches may be using functionality from 3.8+. Proceed with caution, local changes can be made before import
- Any change likely needs to be pip reinstalled (or pushed to the git so the most updated version is used at the start of the notebook)
