### ISSUE TITLE
Add `__all__` Dunder Variables 

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#72]
Hi all, 
The `__all__` dunder variable lives in a script and defines what is accessed by `from ... import *`. At the moment I set it up so that the `__init__.py` selects only the things that we want to import but this can also be done with `__all__` and `*`. I was wondering if we wanted to use `__all__` instead. 

There is no real advantage but it does mean that if a new wavefront class is written in `wavefronts.py` instead of needing to also modify `__init__.py` it can all occur in place as you just append it to `__all__`.

**Comment by LouisDesdoigts** [comment]
Not particularly fussed, but I guess it makes sense to only have to edit one file at a time and be able to see all the classes/functions at the top of a script. Probably worth the switch in the long run, after we suffer through some merge pains 😂
