### ISSUE TITLE
Test and enable 32-bit

### ISSUE THREAD

**Issue by LouisDesdoigts** [LouisDesdoigts/dLux#77]
Currently everything works great using 64-bit but most GPU hardware natively runs 32-bit, resulting in inefficient calculation with 64-bit. The primary limitations of 64-bit originally arose in from a calculation in the MFT code, but this has since been solved. 

Primary testing of 32-bit showed it was able to propagate, but resulted in much less stable gradients that spat out nan's. This testing was *very* minimal so this may be a non-issue. I suspect that the more derivatives are taken, the less stable the gradients are, so actually generating psfs may work fine, but calculating/optimising Fisher matrices may be where problems arise, so this should be where the testing is focused. 

This is ultimately a low-priority issue, as there is presently now work being done that requires super-fast calculations. We are likely to want this in the future for things such real-time AO calculations, possibly running of minimal telescope hardware.

**Comment by benjaminpope** [comment]
“Your scientists were so preoccupied with whether they could, they didn't stop to think if they should.” - how do we go on precision? I am a bit scared of 32 bit!

———————————————
Dr Benjamin Pope (he/him)
Lecturer in Astrophysics
University of Queensland
benjaminpope.github.io
________________________________

**Comment by LouisDesdoigts** [comment]
I've been using 32 bit since this change with no-issues!

**Comment by benjaminpope** [comment]
This will be an issue when we go to high contrast - we will not want to use this by default.

**Comment by LouisDesdoigts** [comment]
I think the only real thing it changes is the 'epsilon' value that you need to add to things that break gradients if you multiply them zero by zero changes from 1e-12 to 1e-8. Might be worth doing a once over and adding a simple if-else on dtype

**Comment by LouisDesdoigts** [comment]
I'm not sure if making the code 50% slower for a small number of cases is the best default behavior....

**Comment by LouisDesdoigts** [comment]
We could print a warning for 32-bit about gradient stability/precision during initialization as a compromise?

**Comment by benjaminpope** [comment]
No seriously, I mean it: if we're doing high dynamic range in coronagraphy, we will care about the _difference_ between PSFs with a factor of 1e6 to 1e9 between them. Bang, you've hit floating point error in float32.

**Comment by benjaminpope** [comment]
I tend to assert that _that precision is always needed in precision optics_ and we should at least have a warning. Except for toy examples, we will always be using float64 in research applications. 

The more important question is which GPUs support double precision with adequate acceleration?

**Comment by LouisDesdoigts** [comment]
Yeah I'll figure out how to raise a warning at import time. Re-opening the issue for this.

**Comment by LouisDesdoigts** [comment]
Done and Done in 0.9 - Warning is printed at init time is jax is not in 64-bit.
