### ISSUE TITLE
Add Logo to README.md and MkDocs Page

### ISSUE THREAD

**Issue by benjaminpope** [LouisDesdoigts/dLux#80]
You have an awesome logo from the SPIE poster - I wonder if we could put up 

- [x] small, square version that could go on the MkDocs page - details https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/ for updating the corner icon and the thumbnail favicon
- [x] full version that can go on README.md in the repo

**Comment by LouisDesdoigts** [comment]
Done and Dusted 😎
