### ISSUE TITLE
2-sided MFT

### ISSUE THREAD

**Issue by benjaminpope** [LouisDesdoigts/dLux#82]
There is a faster version of the matrix DFT, where you apply two matrix operations, one to the left and one to the right. It can only be used for regularly sampled arrays, when the output array is much smaller in dimension than the input array. (For example, in interferometry, mapping big images to a small number of `u,v` coordinates). 

For an example use, see [here](https://github.com/fmartinache/xara/blob/d75e848fdef550d0a0471594e3df933da3dbcc38/xara/core.py#L626) example code to build the two matrices, and [here](https://github.com/fmartinache/xara/blob/d75e848fdef550d0a0471594e3df933da3dbcc38/xara/kpo.py#L264) to apply them, both examples from Frantz Martinache's kernel phase pipeline.

It isn't a bad idea in the long run to build this in

**Comment by LouisDesdoigts** [comment]
I also talked to one of the JPL people working on Toliman after I presented the DP design stuff (Rus I think). They apparently have a n^2 log(n) MFT algorithm. Can't remember the details but also potentially worth investigating in the future as the MFT operations are 99% of our CPU/GPU time.

**Comment by benjaminpope** [comment]
Are you sure you mean n^2 log n? This is just a matrix multiplication

**Comment by LouisDesdoigts** [comment]
I thought it was n^3? I'm not sure, either way Rus said they had a slightly more complex and efficient MFT algorithm. I'll follow it up at some point soon.

**Comment by benjaminpope** [comment]
So as well as Frantz' 2-sided MFT (which is probably good for our application as we have uniform gridding), there is also the Flatiron Institute Non-Uniform Fast Fourier Transform (FINUFFT), with DFM's `jax` bindings here: https://github.com/dfm/jax-finufft

**Comment by LouisDesdoigts** [comment]
Was already implemented all along!
