### ISSUE TITLE
i/o interface to load data

### ISSUE THREAD

**Issue by benjaminpope** [LouisDesdoigts/dLux#87]
When we look at data from JWST, we will often want to take a sub-window of data in a wide field of view image and just look at one PSF there.

We will need to appropriately match the WCS coordinates to the subarray. We can use Astropy for i/o here: https://docs.astropy.org/en/stable/wcs/wcsapi.html#slicing-of-wcs-objects 

It will be important that the ∂Lux WCS system can appropriately read and write this way.

**Comment by LouisDesdoigts** [comment]
This is not functionality we want in dLux, but rather external packages.
