### ISSUE TITLE
OpticalSystem init fails unless you pass wavels, which is an optional argument

### ISSUE THREAD

**Issue by benjaminpope** [LouisDesdoigts/dLux#91]
Title says it all - 

https://github.com/LouisDesdoigts/dLux/blob/5ac32971152fbb82b9f688a0a4cf5ec64c52ae13/dLux/base.py#L86

the `__init__` method of `OpticalSystem` has `wavels=None` as an option, but then it needs the wavels a few lines later at 

https://github.com/LouisDesdoigts/dLux/blob/5ac32971152fbb82b9f688a0a4cf5ec64c52ae13/dLux/base.py#L96

or else it fails.

**Comment by LouisDesdoigts** [comment]
Easy fix with logic. I guess the question is do we want to add a default wavelength or just allow it store `None` and output nothing when `__call__` is called? I would probably say let it be `None` and maybe print a warning.

**Comment by benjaminpope** [comment]
Definitely no default wavelength. I think it should just have a docstring or assert statement or something that makes you add wavelengths.
